import { Context, PromptConfigs, PushPromptConfig } from '../core';
import RootFrame from '../core/root-frame';
export declare type PromptManagerState = 'loading' | 'ready' | 'requesting' | 'requesting-silent' | 'requesting-silent-dismissed' | 'postaction';
export declare class PromptManager {
    private readonly context;
    private readonly pushContainer;
    private readonly triggerFilter;
    private state?;
    private subscriptionState?;
    private activePrompts;
    private currentlyRequestingPrompt?;
    private pushOpsManager?;
    private ui?;
    private publicKey?;
    private prompts;
    private currentPostAction?;
    private channelSubscriptionManager?;
    constructor(ctx: Context, rootFrame: RootFrame, publicKey?: string, prompts?: PromptConfigs<PushPromptConfig>);
    private getChannelSubscriptionManager;
    private onEventTracked;
    private activateDeferredPrompt;
    private onRequestNativePrompt;
    private onPromptAccepted;
    private onPostActionConfirm;
    private onPromptDeclined;
    private onDismissOverlay;
    private hideAndSuppressPrompts;
    private handleUserChannelSelection;
    private render;
    private evaluateTriggers;
    private promptActionNeedsTaken;
    private hidePrompt;
    private activatePrompt;
    private activatePrompts;
    private setState;
    private onEnter;
    private loadPrompts;
}
